.class public Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;
.super Lorg/schabi/newpipe/extractor/stream/Stream;
.source "SubtitlesStream.java"

# interfaces
.implements Ljava/io/Serializable;


# instance fields
.field private final autoGenerated:Z

.field private final code:Ljava/lang/String;

.field private final format:Lorg/schabi/newpipe/extractor/MediaFormat;

.field private final locale:Ljava/util/Locale;

.field private final url:Ljava/lang/String;


# direct methods
.method public constructor <init>(Lorg/schabi/newpipe/extractor/MediaFormat;Ljava/lang/String;Ljava/lang/String;Z)V
    .locals 6

    .line 16
    invoke-direct {p0, p3, p1}, Lorg/schabi/newpipe/extractor/stream/Stream;-><init>(Ljava/lang/String;Lorg/schabi/newpipe/extractor/MediaFormat;)V

    const-string v0, "-"

    .line 23
    invoke-virtual {p2, v0}, Ljava/lang/String;->split(Ljava/lang/String;)[Ljava/lang/String;

    move-result-object v0

    .line 24
    array-length v1, v0

    const/4 v2, 0x1

    const/4 v3, 0x2

    const/4 v4, 0x0

    if-eq v1, v3, :cond_1

    const/4 v5, 0x3

    if-eq v1, v5, :cond_0

    .line 26
    new-instance v1, Ljava/util/Locale;

    aget-object v0, v0, v4

    invoke-direct {v1, v0}, Ljava/util/Locale;-><init>(Ljava/lang/String;)V

    iput-object v1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->locale:Ljava/util/Locale;

    goto :goto_0

    .line 29
    :cond_0
    new-instance v1, Ljava/util/Locale;

    aget-object v4, v0, v4

    aget-object v2, v0, v2

    aget-object v0, v0, v3

    invoke-direct {v1, v4, v2, v0}, Ljava/util/Locale;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    iput-object v1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->locale:Ljava/util/Locale;

    goto :goto_0

    .line 32
    :cond_1
    new-instance v1, Ljava/util/Locale;

    aget-object v3, v0, v4

    aget-object v0, v0, v2

    invoke-direct {v1, v3, v0}, Ljava/util/Locale;-><init>(Ljava/lang/String;Ljava/lang/String;)V

    iput-object v1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->locale:Ljava/util/Locale;

    .line 35
    :goto_0
    iput-object p2, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->code:Ljava/lang/String;

    .line 36
    iput-object p1, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->format:Lorg/schabi/newpipe/extractor/MediaFormat;

    .line 37
    iput-object p3, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->url:Ljava/lang/String;

    .line 38
    iput-boolean p4, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->autoGenerated:Z

    return-void
.end method


# virtual methods
.method public equalStats(Lorg/schabi/newpipe/extractor/stream/Stream;)Z
    .locals 2

    .line 55
    invoke-super {p0, p1}, Lorg/schabi/newpipe/extractor/stream/Stream;->equalStats(Lorg/schabi/newpipe/extractor/stream/Stream;)Z

    move-result v0

    if-eqz v0, :cond_0

    instance-of v0, p1, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;

    if-eqz v0, :cond_0

    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->code:Ljava/lang/String;

    check-cast p1, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;

    iget-object v1, p1, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->code:Ljava/lang/String;

    .line 57
    invoke-virtual {v0, v1}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z

    move-result v0

    if-eqz v0, :cond_0

    iget-boolean v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->autoGenerated:Z

    iget-boolean p1, p1, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->autoGenerated:Z

    if-ne v0, p1, :cond_0

    const/4 p1, 0x1

    goto :goto_0

    :cond_0
    const/4 p1, 0x0

    :goto_0
    return p1
.end method

.method public getDisplayLanguageName()Ljava/lang/String;
    .locals 1

    .line 62
    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->locale:Ljava/util/Locale;

    invoke-virtual {v0, v0}, Ljava/util/Locale;->getDisplayName(Ljava/util/Locale;)Ljava/lang/String;

    move-result-object v0

    return-object v0
.end method

.method public getLanguageTag()Ljava/lang/String;
    .locals 1

    .line 66
    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->code:Ljava/lang/String;

    return-object v0
.end method

.method public getLocale()Ljava/util/Locale;
    .locals 1

    .line 70
    iget-object v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->locale:Ljava/util/Locale;

    return-object v0
.end method

.method public isAutoGenerated()Z
    .locals 1

    .line 50
    iget-boolean v0, p0, Lorg/schabi/newpipe/extractor/stream/SubtitlesStream;->autoGenerated:Z

    return v0
.end method
